CREATE SEQUENCE CLIENT_SEQUENCE START WITH 20 INCREMENT BY 1;
CREATE SEQUENCE ASSURANCE_SEQUENCE START WITH 20 INCREMENT BY 1;

CREATE TABLE COMPTE_BANCAIRE(
	iban varchar(32),
	proprietaire VARCHAR (50),
	swift_code varchar(8),
	PRIMARY KEY (iban)
);


CREATE TABLE CLIENT(
	idClient INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
	comptePrincipal INTEGER,
	primary key (idClient),
        FOREIGN KEY (comptePrincipal) REFERENCES COMPTE_BANCAIRE(iban)
        
);
CREATE TABLE CONTACT(
	contact VARCHAR(20),
        valeur VARCHAR(20)
        id INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
        primary key (id)
        
);


CREATE TABLE PERSONNE_MORALE(
	idClient  ,
	nom varchar(20),
        siren varchar(20),
       
	foreign key (idClient)REFERENCES CLIENT(idClient),
);

CREATE TABLE PERSONNE_PHYSIQUE(
	idClient  INTEGER,
	nom varchar(20),
        prenom varchar(20),
        dateDeNaissance Date,
	foreign key (idClient)REFERENCES CLIENT(idClient),
);




CREATE TABLE COMPTE_CLIENT(
  idClient INTEGER ,
  iban varchar(20),
  PRIMARY KEY (idClient, iban),
    FOREIGN KEY (idClient) REFERENCES CLIENT(idClient),
  FOREIGN KEY (iban) REFERENCES COMPTE_BANCAIRE(iban)
);


create TABLE ASSURANCE(
    idAssurance INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
    typeAssurance varchar(10),
    dateSouscription Date,
    dateAnniversaire Date,
    datePrelevement Date,
    PRIMARY KEY (idAssurance)
  );

CREATE TABLE ASSURANCE_AUTO(
	idAssurance  INTEGER,
	immatriculation varchar(20),
        Bonnus varchar(20),
	foreign key (idAssurance)REFERENCES ASSURANCE(idAssurance),
);

CREATE TABLE ASSURANCE_AUTO(
	idAssurance  INTEGER,
	immatriculation varchar(20),
        Bonnus varchar(20),
	foreign key (idAssurance)REFERENCES ASSURANCE(idAssurance),
);
  create TABLE CLIENT_ASSURANCE(
    idClient INTEGER ,
    idAssurance INTEGER ,
    PRIMARY KEY (idClient, idAssurance),
    FOREIGN KEY (idClient) REFERENCES CLIENT(idClient),
    FOREIGN KEY (idAssurance) REFERENCES ASSURANCE(idAssurance)
  )
